services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\V7\OrderAgent:
        lazy: rue
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: update_payment }
